<%@ Page Title="Shows" MasterPageFile="~/Site.Master" Language="C#" AutoEventWireup="true" CodeBehind="Shows.aspx.cs" Inherits="WebApplication.Shows.Shows" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ShowsGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ShowsGridView_RowCancelingEdit"
            OnRowDeleting="ShowsGridView_RowDeleting"
            OnRowEditing="ShowsGridView_RowEditing"
            OnRowUpdating="ShowsGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ShowsGridView_PageIndexChanging"
            Caption="Shows" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="ShowId" HeaderText="Id" SortExpression="ShowId" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />

                <asp:TemplateField HeaderText="ReleaseDate" SortExpression="ReleaseDate">
                    <EditItemTemplate>
                        <asp:Calendar ID="ReleaseDateCalendar" runat="server" SelectedDate='<%# Bind("ReleaseDate") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ReleaseDate" runat="server" Text='<%# Eval("ReleaseDate") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="Duration" HeaderText="Duration" SortExpression="Duration" />
                <asp:BoundField DataField="Mark" HeaderText="Mark" SortExpression="Mark" />
                <asp:BoundField DataField="MarkMonth" HeaderText="Mark Month" SortExpression="MarkMonth" />
                <asp:BoundField DataField="MarkYear" HeaderText="Mark Year" SortExpression="MarkYear" />

                <asp:TemplateField HeaderText="Genre" SortExpression="Genre.GenreName">
                    <EditItemTemplate>
                        <asp:DropDownList ID="GenreDropDownList" DataSourceID="GenresSqlDataSource" DataValueField="GenreId" DataTextField="GenreName" runat="server"  SelectedValue='<%# Bind("GenreId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="GenreId" runat="server" Text='<%# Eval("Genre.GenreName") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Desciption" />
            </Columns>
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add show</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="ShowNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Relesead date: </span>
            <asp:Calendar ID="ShowReleaseDateTextBox" runat="server"></asp:Calendar>
        </div>

        <div>
            <span>Duration: </span>
            <asp:TextBox ID="ShowDurationTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Mark: </span>
            <asp:TextBox ID="ShowMarkTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Mark month: </span>
            <asp:TextBox ID="ShowMarkMonthTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Mark year: </span>
            <asp:TextBox ID="ShowMarkYearTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Genre: </span>
            <asp:DropDownList ID="GenreDropDownList" DataSourceID="GenresSqlDataSource" DataValueField="GenreId" DataTextField="GenreName" runat="server"></asp:DropDownList>
        </div>

        <div>
            <span>Description: </span>
            <asp:TextBox ID="ShowDescriptionTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddShowButton" runat="server" Text="Add show" OnClick="AddShowButton_Click" />
        </div>
    </div>


    
    <asp:SqlDataSource ID="GenresSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [GenreId], [GenreName] FROM [Genres]">
    </asp:SqlDataSource>
</asp:Content>

