<%@ Page Title="Genres" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Genres.aspx.cs" Inherits="WebApplication.Genres.Genres" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="GenresGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="GenresGridView_RowCancelingEdit"
            OnRowDeleting="GenresGridView_RowDeleting"
            OnRowEditing="GenresGridView_RowEditing" 
            OnRowUpdating="GenresGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="GenresGridView_PageIndexChanging"
            Caption="Genres" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="GenreId" HeaderText="Id" SortExpression="GenreId" ReadOnly="true" />    
                <asp:BoundField DataField="GenreName" HeaderText="Name" SortExpression="GenreName" />
                <asp:BoundField DataField="GenreDescription" HeaderText="Description" SortExpression="GenreDescription" />
            </Columns>
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add genre</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="GenreNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Description: </span>
            <asp:TextBox ID="GenreDescriptionTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddGenreButton" runat="server" Text="Add genre" OnClick="AddGenreButton_Click" />
        </div>
    </div>
    
</asp:Content>
