<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Timetables.aspx.cs" Inherits="WebApplication.Timetables.Timetables" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="TimetablesGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="TimetablesGridView_RowCancelingEdit"
            OnRowDeleting="TimetablesGridView_RowDeleting"
            OnRowEditing="TimetablesGridView_RowEditing"
            OnRowUpdating="TimetablesGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="TimetablesGridView_PageIndexChanging"
            Caption="Timetables" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="TimetableId" HeaderText="Id" SortExpression="TimetableId" ReadOnly="true" />    
                <asp:BoundField DataField="DayOfWeek" HeaderText="Day Of Week" SortExpression="DayOfWeek" />
                <asp:BoundField DataField="Month" HeaderText="Month" SortExpression="Month" />
                <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />

                <asp:TemplateField HeaderText="Show" SortExpression="Show.Name">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ShowDropDownList" DataSourceID="ShowsSqlDataSource" DataValueField="ShowId" DataTextField="Name" runat="server"  SelectedValue='<%# Bind("ShowId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ShowId" runat="server" Text='<%# Eval("Show.Name") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="StartTime" HeaderText="Start Time" SortExpression="StartTime" />
                <asp:BoundField DataField="EndTime" HeaderText="End Time" SortExpression="EndTime" ReadOnly="true"/>
            </Columns>
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add timetable</h2>

        <div>
            <span>Day Of Week: </span>
            <asp:TextBox ID="TimetableDayOfWeekTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Month: </span>
            <asp:TextBox ID="TimetableMonthTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Year: </span>
            <asp:TextBox ID="TimetableYearTextBox" runat="server"></asp:TextBox>
        </div>

        
        <div>
            <span>Genre: </span>
            <asp:DropDownList ID="ShowsDropDownList" DataSourceID="ShowsSqlDataSource" DataValueField="ShowId" DataTextField="Name" runat="server"></asp:DropDownList>
        </div>

        <div>
            <span>Start Time: </span>
            <asp:TextBox ID="TimetableStartTimeTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddTimetableButton" runat="server" Text="Add show" OnClick="AddTimetableButton_Click" />
        </div>
    </div>


    
    <asp:SqlDataSource ID="ShowsSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [ShowId], [Name] FROM [Shows]">
    </asp:SqlDataSource>
</asp:Content>
